repos:
  # Rust tools
  - repo: https://github.com/AndrejOrsula/pre-commit-cargo
    rev: 0.4.0
    hooks:
      - id: cargo-fmt
      - id: cargo-clippy
        args: ["--all-targets", "--all-features", "--", "-D", "warnings"]
      - id: cargo-check
        args: ["--all-targets", "--all-features"]
      - id: cargo-test
        args: ["--all-targets", "--all-features", "--", "--test-threads=1"]
      - id: cargo-test-doc
        args: ["--all-features"]

  # Conventional Commits
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.22.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
