= Bicep Docs
:toc:
:toc-title: Table of Contents
:sectnums:

A documentation generator for Azure Bicep files, similar to `terraform-docs`.

== Overview

`bicep-docs` is a documentation generator for Azure Bicep files, similar to `terraform-docs`.
It works by parsing the Bicep file and extracting information about the parameters, variables, and outputs.
This information is then used to generate documentation in various formats, such as Markdown, AsciiDoc, YAML, and JSON.

=== Why `bicep-docs`?

That is an excellent question.
When I first started looking at automating my Bicep documentation, the main tool I found was link:https://github.com/Azure/PSDocs.Azure[PSDocs for Azure].
I had three main complaints with PSDocs, which (admittedly) are related.
The first was the lack of link:https://github.com/Azure/PSDocs.Azure/issues/106[Native support for Bicep files].
This means documenting a Bicep file required compilation to ARM, which led to the other two problems.

Problem two is, honestly, minor.
Because of the requirement to compile to ARM, documentation required the full Bicep stack.
Which is fine when you are deploying the Bicep, but is overkill when you just want to generate/validate the documentation in a pipeline.
Admittedly, in the pipeline you probably already have the Bicep CLI installed, so there is no extra time spent installing it.

Problem three, however, is the one that motivated me to action.
Because of the compilation to ARM, many of the nuances of a Bicep template get lost in the documentation.
For example, I like to use a central Bicep module with common types and functions that I'll need frequently.
When the Bicep file is compiled to ARM, these functions are fetched and compiled into the document.
This is needed for deployment, but bloats the documentation of my file and also hides the fact of the shared module ecosystem.
The same problem occurs when referencing local modules.

In addition, when the Bicep modules are merged into the compiled template, the names are changed to generic names.
If the same function or variable is imported multiple times, each gets a unique name in the compiled template.
This makes tracing the usage throughout the documentation impossible, and also bloats the documentation.

== Installation

Download the latest release from link:releases/[GitHub].
Extract the downloaded file and ensure it is placed into your path.

== Basic Usage

[source,bash]
----
Usage: bicep-docs <FORMAT> [OPTIONS]  <BICEP FILE>

Formats:
  markdown  Document Bicep file in Markdown format
  asciidoc  Document Bicep file in AsciiDoc format
  yaml      Document Bicep file in YAML format
  json      Document Bicep file in JSON format
  help      Print this message or the help of the given subcommand(s)

Global Options:
  -v, --verbose...               Set the verbosity level of output (v: debug, vv: trace)
  -q, --quiet                    Don't show any logging output
      --log-format <LOG_FORMAT>  Set the format for logging output [default: text] [possible values: text, json]
      --log-file <LOG_FILE>      Path to a file to write logs to (instead of stdout/stderr)
  -h, --help                     Print help
  -V, --version                  Print version

Format Options:
  -o, --output <OUTPUT>  Output file path. Defaults to input filename with appropriate extension
      --emoji            Enable emoji usage in documentation output
      --exclude-empty    Skip exporting empty sections in the documentation
  -h, --help             Print help
----

Examples of the documentation output are available in the link:examples/[Examples] directory.
