name: Copilot Development Environment Setup

on: workflow_dispatch

permissions:
  contents: read

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt, miri

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install cargo-update
        run: cargo install cargo-update --locked

      - name: Install cargo-deny
        run: cargo install cargo-deny --locked

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Cache npm packages
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }} # Adjust if you have global package list
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Or your preferred version

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Install pre-commit hooks
        run: pre-commit install --install-hooks

      - name: Install commitlint and conventional config
        run: npm install -g @commitlint/cli @commitlint/config-conventional

      - name: Verify tool installations
        run: |
          rustc --version
          cargo --version
          cargo clippy --version
          cargo fmt --version
          cargo miri --version
          cargo-update --version
          cargo-deny --version
          python --version
          pip --version
          pre-commit --version
          node --version
          npm --version
          commitlint --version
